dist: trusty
language: cpp
compiler: gcc

git:
  depth: 3

addons:
  apt:
    packages:
      - cmake
      - libpango1.0-dev
      - libx11-dev
      - libxcursor-dev
      - libxext-dev
      - libxfixes-dev
      - libxft-dev
      - libxinerama-dev
      - qtbase5-dev

script:
  - ./build.sh

after_success:
  - #mkdir out && cp build/fltk_dialog/fltk-dialog out/
  - #test $TRAVIS_BRANCH != master || bash ./.upload.sh out/*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
