dist: trusty
language: cpp
compiler: gcc

git:
  depth: 3

addons:
  apt:
    packages:
      - cmake
      - libmagic-dev
      - libpango1.0-dev
      - libx11-dev
      - libxcursor-dev
      - libxext-dev
      - libxfixes-dev
      - libxft-dev
      - libxinerama-dev
      - qtbase5-dev
      - wget

script:
  - # regular test build
  - ./build.sh
  - # build AppImage to upload
  - ./build.sh --disable-dlopen

after_success:
  - test $TRAVIS_BRANCH != master || bash ./.upload.sh build/fltk-dialog-*.AppImage

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
