dist: trusty
language: cpp
compiler: gcc

addons:
  apt:
    packages:
      - autoconf
      - libx11-dev
      - libxcursor-dev
      - libxext-dev
      - libxfixes-dev
      - libxft-dev
      - libxinerama-dev
      - cmake
      - libqt4-dev
      - qtbase5-dev

script:
  - ./autogen.sh && ./configure --enable-hardening && make -j4 V=1

after_success:
  - mkdir out && cp fltk-dialog out/ && strip --strip-all out/fltk-dialog
  - test $TRAVIS_BRANCH != master || bash ./.upload.sh out/*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
