#ifndef FLTK_DIALOG_MAIN_HPP
#define FLTK_DIALOG_MAIN_HPP

/* dialog types */
enum dialogTypes
{
  DIALOG_ABOUT,
  DIALOG_ALERT,
  DIALOG_DROPDOWN,
  DIALOG_DND,
  DIALOG_FDATE,
  DIALOG_HTML,
  DIALOG_NOTIFY,
  DIALOG_TEXTINFO,
  DIALOG_FL_CALENDAR,
  DIALOG_FL_CHECK_BUTTON,
  DIALOG_FL_CHOICE,
  DIALOG_FL_COLOR,
  DIALOG_FL_DIR_CHOOSER,
  DIALOG_FL_FILE_CHOOSER,
  DIALOG_FL_INPUT,
  DIALOG_FL_MESSAGE,
  DIALOG_FL_PASSWORD,
  DIALOG_FL_PROGRESS,
  DIALOG_FL_RADIO_ROUND_BUTTON,
  DIALOG_FL_VALUE_SLIDER
};

/* getopt long_options */
enum longOpts
{
  LO_ABOUT,
  LO_ALT_LABEL,
  LO_AUTO_CLOSE,
  LO_AUTO_SCROLL,
  LO_CALENDAR,
  LO_CANCEL_LABEL,
  LO_CHECKBOX,
  LO_CHECKLIST,
  LO_CLOSE_LABEL,
  LO_COLOR,
  LO_DIRECTORY,
  LO_DATE,
  LO_DND,
  LO_DROPDOWN,
  LO_ENTRY,
  LO_FILE,
  LO_FORMAT,
  LO_HTML,
  LO_MESSAGE,
  LO_MAX_VALUE,
  LO_MIN_VALUE,
  LO_NATIVE,
  LO_NO_CANCEL,
  LO_NO_ESCAPE,
  LO_NO_LABEL,
  LO_NOTIFY,
  LO_NOTIFY_ICON,
  LO_OK_LABEL,
  LO_PASSWORD,
  LO_PROGRESS,
  LO_RETURN_NUMBER,
  LO_QUESTION,
  LO_RADIOLIST,
  LO_SCALE,
  LO_SCHEME,
  LO_STEP,
  LO_TEXT,
  LO_TEXT_INFO,
  LO_TIMEOUT,
  LO_TITLE,
  LO_VALUE,
  LO_WARNING,
  LO_WINDOW_ICON,
  LO_YES_LABEL
};

#endif  /* !FLTK_DIALOG_MAIN_HPP */

